#pragma config(Motor,  motorA,          kiwiA,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          kiwiB,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          kiwiC,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"


void motorTrigger(tMotor motorCall,int x,int y,int z)
{
	motor[motorCall]= (y+x+z);
}
task FPSDrive()
{
	while(true)
	{
		//int gyroValue = SensorValue(Gyro); //set gyroscope value to gyroValue

		//nxtDisplayCenteredBigTextLine(5,"%d",gyroValue); //display gyroValue to NXT
		//nxtDisplayCenteredBigTextLine(5,"%d",accelValue); //display accelValue to NXT

		getJoystickSettings(joystick);

		int y= joystick.joy1_y1;
		int x= joystick.joy1_x1;
		int z= joystick.joy1_x2;

		//int trueX = (cosDegrees(currHeading+calibrate)*x)-(sinDegrees(currHeading+calibrate)*y); //sets trueX to rotated x value
		//int trueY = (sinDegrees(currHeading+calibrate)*x)+(cosDegrees(currHeading+calibrate)*y); //sets trueY to rotated y value

		motor[kiwiA] = x + z;
		motor[kiwiB] = (.5*x)+(.5*y) + z;
		motor[kiwiC] = -(.5*x)-(.5*y)+ z;

		//accelValue = SensorValue(Accel);
		//accelValue /= 200;


		//lightValue = SensorValue(Light);


	}
}

void kiwiMove()
{
	motor[kiwiA] = 50;
	motor[kiwiB] = 50;
	motor[kiwiC] = 50;
}
void drive()
{
}


task main()
{
	waitforStart();
	startTask(FPSDrive);
	getJoystickSettings(joystick);
	kiwiMove();
	while(true)
	{
		wait1Msec(1000);
	}
}
