#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S3, HTTMUX,         sensorHiTechnicTouchMux)
#pragma config(Motor,  mtr_S1_C1_1,     ring,          tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C1_2,     finger,        tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_1,     up1,           tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_2,     up2,           tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_1,     backright,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     frontright,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     backleft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     frontleft,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    IRlift,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    claw,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    elbow,                tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    shoulder,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    ,             tServoNone)
#pragma config(Servo,  srvo_S2_C2_3,    rings,                tServoStandard)
#pragma config(Servo,  srvo_S2_C2_4,    IRpivot,              tServoStandard)
#pragma config(Servo,  srvo_S2_C2_5,    release,              tServoStandard)
#pragma config(Servo,  srvo_S2_C2_6,    flip,                 tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment\Sample Programs\NXT\3rd Party Sensor Drivers\drivers\hitechnic-touchmux.h"
#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment\Sample Programs\NXT\3rd Party Sensor Drivers\drivers\lego-touch.h"

void initializeRobot()
{


	return;
}

task main()
{
	// This is the code to define the variables for direct mecanum code.
	SensorType[S3] = sensorHiTechnicTouchMux;

	bool button1 = false;
	bool button2 = false;
	bool button3 = false;
	bool button4 = false;

	initializeRobot();

	waitForStart();

	while(true)

	{
		getJoystickSettings(joystick);



		if(joy1Btn(4))
		{
			button4 = true;

			nMotorEncoderTarget[motorA] = 10;

			motor[up1]=-50;
			motor[up2]=-50;
			while(nMotorRunState[motorA] != runStateIdle)
			{}

			motor[up1]=0;
			motor[up2]=0;

			button1 = false;
			button2 = false;
			button3 = false;
		}

		else if(joy1Btn(3))
		{
			button3 = true;

			nMotorEncoderTarget[motorA] = 1080;

			motor[up1]=100;
			motor[up2]=100;
			while(nMotorRunState[motorA] != runStateIdle)
			{}

			motor[up1]=0;
			motor[up2]=0;

			button1 = false;
			button2 = false;
			button4 = false;
		}

		else if(joy1Btn(2))
		{
			button2 = true;

			nMotorEncoderTarget[motorA] = 720;

			if(button1 || button4)
			{
				motor[up1]=100;
				motor[up2]=100;

				while(nMotorRunState[motorA] != runStateIdle)
				{}

				motor[up1]=0;
				motor[up2]=0;

				button1 = false;
				button4 = false;
			}

			else if(button3)
			{
				motor[up1]=-50;
				motor[up2]=-50;

				while(nMotorRunState[motorA] != runStateIdle)
				{}

				motor[up1]=0;
				motor[up2]=0;

				button3 = false;
			}
		}

		else if(joy1Btn(1))
		{
			button1 = true;

			nMotorEncoderTarget[motorA] = 360;

			if(button2 || button3)
			{
				motor[up1]=-50;
				motor[up2]=-50;

				while(nMotorRunState[motorA] != runStateIdle)
				{}

				motor[up1]=0;
				motor[up2]=0;

				button2 = false;
				button3 = false;
			}

			else if(button4)
			{
				motor[up1]=100;
				motor[up2]=100;

				while(nMotorRunState[motorA] != runStateIdle)
				{}

				motor[up1]=0;
				motor[up2]=0;

				button4 = false;
			}

		}

		else
		{
			motor[up1]=0;
			motor[up2]=0;
		}
	}
}
