#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S3, HTTMUX,         sensorHiTechnicTouchMux)
#pragma config(Motor,  mtr_S1_C1_1,     ring,          tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C1_2,     finger,        tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_1,     up1,           tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_2,     up2,           tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_1,     backright,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     frontright,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     backleft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     frontleft,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    IRlift,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    claw,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    elbow,                tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    servo7,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    shoulder,             tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    rings,                tServoStandard)
#pragma config(Servo,  srvo_S2_C2_4,    IRpivot,              tServoStandard)
#pragma config(Servo,  srvo_S2_C2_5,    release,              tServoStandard)
#pragma config(Servo,  srvo_S2_C2_6,    flip,                 tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment\Sample Programs\NXT\3rd Party Sensor Drivers\drivers\hitechnic-touchmux.h"
#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment\Sample Programs\NXT\3rd Party Sensor Drivers\drivers\lego-touch.h"

void initializeRobot()
{


	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	return;
}

void servotoggle(short buttonname, bool Pressedornot, TServoIndex servoName, int lower, int upper)
{
	if(buttonname)
		{
			int mid = (lower + upper) / 2;
			if(!Pressedornot)
			{
				Pressedornot = true;

				if(ServoValue[servoName]>mid)
				{
					servo[servoName]=lower;
				}
				else
				{
					servo[servoName]=upper;
				}
			}
		}
		else
		{
			Pressedornot = false;
		}
}

task main()
{

	bool alreadyPressed = false;

	initializeRobot();

	waitForStart();


	while(true)

	{
		if(joy2Btn(1))
		{
			if(!alreadyPressed)
			{
				alreadyPressed = true;

				if(ServoValue[rings]>100)
				{
					servo[rings]=0;
				}
				else
				{
					servo[rings]=255;
				}
			}
		}
		else
		{
			alreadyPressed = false;
		}

		servotoggle(joy1Btn(1), alreadyPressed, rings, 0,255);
	}
}

void servotoggle(short buttonname, bool Pressedornot, TServoIndex servoName, int lower, int upper)
{
	if(buttonname)
		{
			int mid = (lower + upper) / 2;
			if(!Pressedornot)
			{
				Pressedornot = true;

				if(ServoValue[servoName]>mid)
				{
					servo[servoName]=lower;
				}
				else
				{
					servo[servoName]=upper;
				}
			}
		}
		else
		{
			Pressedornot = false;
		}
}


// sokolov function 6for toggleservo

/* global variables
        String servoName;
        int start, finish;

        ... main...
        while (true){
        if(joy1Btn(5)){
            //do you want to check which is greater, or know start is < end?
            servoName = "xxx"
            start = 0;
            end = 255;
            toggleServo(servoName, start, end);
            }
       }//end true
*/
       void toggleServo(string servoName, int start, int end)
       {
            int mid = (start+end)/2;
           if(servo[servoName]>mid){
               servo[servoName] = start;
           }else{
               servo[servoName] = end;
           }//end if
      }//end void
