#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     HTTMUX,         sensorHiTechnicTouchMux)
#pragma config(Motor,  mtr_S1_C1_1,      ,             tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C1_2,      ,             tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_1,      ,             tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_2,      ,             tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_1,     frontleft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     backleft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     frontright,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     backright,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    servo7,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void initializeRobot()
{
// Place code here to sinitialize servos to starting positions.
// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
return;
}
//accuracy threshold for driving on joysticks
int thresabs(int n){
if(abs(n) < 10){
n=0;
}
return (100*n/128);
}

task main()
{
// This is the code to define the variables for direct mecanum code.

initializeRobot();

waitForStart();

while(true)

{
getJoystickSettings(joystick);

int x = thresabs(joystick.joy1_x2);
int y = thresabs(joystick.joy1_y2);
int z = thresabs(joystick.joy1_y1);
//if drive does not work, delete from here

if(joystick.joy1_TopHat==0)
{
motor[frontleft]=100;
motor[backleft]=100;
motor[frontright]=-100;
motor[backright]=-100;
}

else if(joystick.joy1_TopHat==2)
{
motor[frontleft]=100;
motor[backleft]=-100;
motor[frontright]=100;
motor[backright]=-100;
}

else if(joystick.joy1_TopHat==4)
{
motor[frontleft]=-100;
motor[backleft]=-100;
motor[frontright]=100;
motor[backright]=100;
}

else if(joystick.joy1_TopHat==6)
{
motor[frontleft]=-100;
motor[backleft]=100;
motor[frontright]=-100;
motor[backright]=100;
}

else if(joy2Btn(6))
{
motor[frontleft]=75;
motor[backleft]=-75;
motor[frontright]=75;
motor[backright]=-75;
wait1Msec(10);
}

else if(joy2Btn(8))
{
motor[frontleft]=-75;
motor[backleft]=75;
motor[frontright]=-75;
motor[backright]=75;
wait1Msec(10);
}

else
{
motor[frontleft]=y+x+z;
motor[backleft]=y-x+z;
motor[frontright]=-(y-x-z);
motor[backright]=-(y+x-z);
}
//and also delete from here
}


}
