#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     IR_LEFT,        sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     frontRight,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     backRight,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift2,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     frontLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     backLeft,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     collector,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     collector2,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    rollingGoalLeft,      tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    rollingGoalRight,     tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "infraredSensor.c"
#include "hitechnic-gyro.h"
#include "Collector.c"
#include "RollingGoal.c"
#include "Dump.c"
#include "encoderFunctions.c"
#include "moveFunctions.c"
#include "gyrofunctions.c"

task main()
{
	initializeRobot();
	StartTask(getHeading);
	wait1Msec(1000);
	coastTo(6);
	wait1Msec(3000);
	coastTo(12);
	wait1Msec(3000);
	rotateCoast(45,1);
	wait1Msec(3000);
	coastTo(40);
	wait1Msec(3000);
	coastTo(-40);
	rotateCoast(45,-1);
	coastTo(-18);

	/*
	coastTicks(200);
	wait1Msec(500);
	rotate(6,-1);
	wait1Msec(500);
	coastTicks(2122);
	wait1Msec(500);
	raiseLift();
	rotate(38, 1);
	wait1Msec(400);
	coastFor(11);
	wait1Msec(1000);
	advBrakeNeg();
	dumpAll();
	dumpAll();
	lowerLift();
	while(true)
	wait1Msec(1000);
	*/
	/*
	This is the last position, just tweak the skeleton
	at the end everything has to go into auton_centergoal.c
	position 2 is done, position 1 is above, position 0 is this
	*/

/*
	coastTo(5);
	wait1Msec(500);
	rotate(30,1);
	wait1Msec(500);
	coastTicks(1000);
	wait1Msec(1000);
	rotate(33,-1);
	raiseLift();
	advBrakeNeg();
	coastTo(62);
	wait1Msec(500);
	dumpAll();
	dumpAll();
	coastFor(-11);
	lowerLift();
	*/
}
