#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     IR_LEFT,        sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     frontRight,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     backRight,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift2,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     frontLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     backLeft,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     collector,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     collector2,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    rollingGoalLeft,      tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    rollingGoalRight,     tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "infraredSensor.c"
#include "hitechnic-gyro.h"
#include "Collector.c"
#include "RollingGoal.c"
#include "Dump.c"
#include "encoderFunctions.c"
#include "moveFunctions.c"
#include "gyrofunctions.c"

task display()
{
	while (true){
		eraseDisplay();
		nxtDisplayTextLine(0,"Act:%d",nMotorEncoder[frontLeft]);
		//nxtDisplayCenteredTextLine(0, "Heading: %d", currHeading);
		//nxtDisplayCenteredTextLine(2, "Sonar: %d", sonarValue);
		wait1Msec(20);
	}
}

task servoInit() {
	while(true)
		servo[dump] = 66;
}

task main()
{
	initializeRobot();
	StartTask(getHeading);
	startTask(readPosition);
	//waitForStart();
	servo[dump] = 94+PI;
	coastTo(-60);
	wait1Msec(200);
	rotateCoast(90,-1);
	wait1Msec(200);
	coastTo(-90); //move to center goal
	wait1Msec(200);
	coastFor(-30);
	wait1Msec(200);
	rotateCoast(45,-1);
	wait1Msec(200);
	coastTo(-60);
	coastFor(-60);
	wait1Msec(200);
	rotateCoast(45,1);
	wait1Msec(200);
	coastTo(-36);
	wait1Msec(300);
	rotateCoast(90,1)
	wait1Msec(400);
	coastFor(-63);
	//Neccessary do not touch

	wait1Msec(500);
	servo[dump] = 66;
	playSound(soundDownwardTones);
	while(irPosition < 0){}
	wait1Msec(500);

	if(irPosition == 2)
	{
		playSound(soundUpwardTones);
		coastTo(-2);
		encRot(-3);
		coastTicks(3300);
		encRot(-180-94);
		wait1Msec(500);
		raiseLift();
		advBrakeNeg();
		encRot(-10);
		coastFor(20);//bad code
		dumpAll();
		coastFor(-3);
		dumpAll();
		lowerLift();
		coastFor(-10);
		rotate(30,1);
		coastTo(-150);
		while(true)
			wait1Msec(1000);
	}

	else if(irPosition == 1)
	{
		playSound(soundDownwardTones);
		coastTicks(200);
		rotate(10,-1);
		coastTicks(1800);
		rotate(40.5, 1);
		coastFor(27);
		wait1Msec(200);
		raiseLift();
		coastFor(3);
		advBrakeNeg();
		dumpAll();
		dumpAll();
		coastFor(-3);
		lowerLift();
		encRot(-270);
		coastTo(-29);
		encRot(-83);
		coastTo(-120);
		while(true) wait1Msec(1000);
	}

	else if(irPosition == 0)
	{
		coastTo(5);
		rotate(30,1);
		coastTicks(900);
		rotate(35,-1);
		coastTo(44);
		wait1Msec(500);
		raiseLift();
		advBrakeNeg();
		coastTo(21);
		rotate(10,-1);
		dumpAll();
		dumpAll();
		coastFor(-11);
		wait1Msec(500);
		lowerLift();
		encRot(-267);
		coastTo(-34);
		encRot(-96);
		coastTo(-120);
	}

	playSound(soundUpwardTones);
	wait1Msec(5000000);

}
