#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustom9V)
#pragma config(Motor,  mtr_S1_C1_1,     frontRight,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     backRight,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift2,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     frontLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     backLeft,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     collector,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     collector2,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    rollingGoalPair,      tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    flag,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "autonUtils.c" //included for the dclarations below
//include these after so they can use the above declarations
//#include "wPZDAll.c"
//#include "wPZDCenter.c"
//#include "wPZDRamp.c"
//#include "wPZDScore.c"
#include "wPZScoreTemp.c"
//#include "wRScore.c"
//#include "wRNoScore.c"
//these new files are dependent on auton_chooser for a lot so use the longer file names for independent usage
int startingPos=-1;
int action=-1;
int autonomous = -1;

void convertToName(int auton){
	switch(auton)
	{
	case 0: nxtDisplayCenteredTextLine(0,"Park: Def (All)"); break;
	case 1: nxtDisplayCenteredTextLine(0,"Park: Def->Center"); break;
	case 2: nxtDisplayCenteredTextLine(0,"Park: Def->Ramp"); break;
	case 3: nxtDisplayCenteredTextLine(0,"Park: Def & Score"); break;
	case 4: nxtDisplayCenteredTextLine(0,"Park: Score"); break;
	case 5: nxtDisplayCenteredTextLine(0,"Ramp: Score"); break;
	case 6: nxtDisplayCenteredTextLine(0,"Ramp: Go Down"); break;
	default: nxtDisplayCenteredTextLine(0,"No Auton"); break;
	}
}

void calm()
{
	wait1Msec(600);
}

task main {
	initializeRobot();
	nxtDisplayCenteredTextLine(2,"< Parking");
	nxtDisplayCenteredTextLine(3,"Ramp >");
	while(startingPos<0)
	{
		if(nNxtButtonPressed==2) startingPos = 1;
		if(nNxtButtonPressed==1) startingPos = 2;
	}
	calm();
	if(startingPos==2)
	{
		nxtDisplayCenteredTextLine(2,"< Score");
		nxtDisplayCenteredTextLine(3,"Don't :D >");
		while(autonomous<0)
		{
			if(nNxtButtonPressed==2) autonomous = 5;
			if(nNxtButtonPressed==1) autonomous = 6;
		}
	}
	else{
		nxtDisplayCenteredTextLine(2,"< Defend");
		nxtDisplayCenteredTextLine(3,"Both O");
		nxtDisplayCenteredTextLine(4,"Score >");
		while(action<0)
		{
			if(nNxtButtonPressed==2) action = 1; //defend
				if(nNxtButtonPressed==1) action = 2; //score
				if(nNxtButtonPressed==3) action = 3; //both
		}
		calm();
		if(action == 1)
		{ //if only defend
			nxtDisplayCenteredTextLine(0,"Defend what?");
			nxtDisplayCenteredTextLine(2,"< Center");
			nxtDisplayCenteredTextLine(3,"Both O");
			nxtDisplayCenteredTextLine(4,"Ramp >");
			while(autonomous<0)
			{
				if(nNxtButtonPressed==2) autonomous = 1;
				if(nNxtButtonPressed==1) autonomous = 2;
				if(nNxtButtonPressed==3) autonomous = 0;
			}
		}

		if(action == 2) //if only score
			autonomous=4;
		if(action == 3)
			autonomous=3;

	}

	eraseDisplay();
	convertToName(autonomous);
//	initializeRobot();
	//waitForStart();

	switch(autonomous)
	{
	//	case 0: startTask(defenseAll); break;
	//	case 1: startTask(centerDefense); break;
	//	case 2:  startTask(defenseRamp); break;
	//	case 3:  startTask(defenseScore); break;
		case 4:  startTask(parkScore); break;
	//	case 5:  startTask(rampScore);break;
	//	case 6:  startTask(rampOff); break;
		default:  break;
	}
while(true) wait1Msec(10000000000000000000000000);
}
