#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustom9V)
#pragma config(Motor,  mtr_S1_C1_1,     frontRight,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     backRight,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift2,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     frontLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     backLeft,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     collector,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     collector2,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    rollingGoalPair,      tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    flag,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    servo7,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    servo8,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/*


INSTRUCTIONS PLEASE READ AJ!!! Do not edit this file.
1. Compile this to make sure no errors (you'll have to sync google drive, or download all the include files seperately)
2. Download to the NXT on the robot.
3. If you get any errors at this point message me.
4. Run it through the NXT and watch magics happen. If anything doesn't work properly, don't try to fix it, message me.
5. After 5 runs, turn everything off. Do not do the ramp code.



*/



#include "moveFunctions.c"
//#include "Robotics (PROGRAMENG)/hitechnic-superpro.h"
#include "clampFlagTest.c"
int presses = 0;
bool isPressed = false;
bool clamped = false;
void raiseLift2() {
				motor[motorLift2]=-90;
				motor[motorLift1]=-90;
				wait1Msec(50);
				while(abs(nMotorEncoder[motorLift2])<(1440*2.4 ))
				{
				}
				motor[motorLift1] = 0;
				motor[motorLift2] = 0;
				nMotorEncoder[motorLift2] = 0;
			}
void lowerLift2() {
				motor[motorLift2]=90;
				motor[motorLift1]=90;
				wait1Msec(50);
				while(abs(nMotorEncoder[motorLift2])<(1440*2.4))
				{
				}
				motor[motorLift1] = 0;
				motor[motorLift2] = 0;
				nMotorEncoder[motorLift2] = 0;
}

void raiseLift3() {
				motor[motorLift2]=-90;
				motor[motorLift1]=-90;
				wait1Msec(50);
				while(abs(nMotorEncoder[motorLift2])<(1440*2.4 ))
				{
				}
				motor[motorLift1] = 0;
				motor[motorLift2] = 0;
				nMotorEncoder[motorLift2] = 0;
			}
void lowerLift3() {
				motor[motorLift2]=90;
				motor[motorLift1]=90;
				wait1Msec(50);
				while(abs(nMotorEncoder[motorLift2])<(1440*2.4))
				{
				}
				motor[motorLift1] = 0;
				motor[motorLift2] = 0;
				nMotorEncoder[motorLift2] = 0;
}

void collectJudges(int x)
{
	motor[collector] = x;
	motor[collector2] = -x;
}

task main()
	{
		servo[rollingGoalPair] = 172;
		startTask(autoRollingGoal);
		presses = 0;
		isPressed = false;
		while(true){
				if(nNxtButtonPressed == 3) {presses++; wait1Msec(500); isPressed = true;}
				switch(presses)
				{
					case 1: if(isPressed){collectJudges(78); wait1Msec(1500); collectJudges(0); isPressed = false;} break;
					case 2: if(isPressed){raiseLift3(); isPressed = false; servo[dump] = 180; isPressed = false; wait1Msec(500); } break;
					case 3: if(isPressed){servo[dump] = 75; lowerLift3(); isPressed = false;} break;
	//			case 4: if(isPressed){ p
				//case 6: if(pressed){ HTSPBwriteIO(HTSPB, 0x04); wait1Msec(1000); HTSPBwriteIO(HTSPB, 0x00); pressed = false; } break;
					//not using protoboard anymore
				}

	}

}
