#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustom9V)
#pragma config(Motor,  mtr_S1_C1_1,     frontRight,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     backRight,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift2,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     frontLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     backLeft,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     collector,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     collector2,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    rollingGoalPair,      tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    flag,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-sensormux.h"
#include "lego-ultrasound.h"
#include "autonUtils.c"
#include "EOPD.c"
#include "clampFlagTest.c"

int sonarPosition;

float sonargetter;

bool resetPos() {
	coastTo(0.5);
	strafe(left,medium);
	while(floorColor == GRAY){	}
	playSound(soundBeepBeep);
	brake();
	strafeTo(-7);
	coastTo(-5);
	return true;
}

void parkingZoneCenterGoal()
{
	servo[dump]=75;
	initializeRobot();
	StartTask(getHeading);

	//defensive here
	//////////////////////////////////////////////////////////////////////////////////////////////////////////
	//defensive close
	/*
	StartTask(readEOPD);
	resetPos();*/
//	diagonalTo((24*sqrt(2))-(13*sqrt(2)),55);


	/*
	rotateCoast(25, -1);
	coastTo(75);
	rotateCoast(25, 1);
	coastTo(-45);
	strafeTo(-40);
	coastTo(-15);
*/


//	while(true) wait1msec(1000);

	strafeTo(-13);
	coastTo(33)
	wait1Msec(1000);
	sonarPosition = getPosition();


	if(sonarPosition==1)
	{
		rotateCoast(45,-1);
		strafeTo(-15);
		//^^ This just aligns to the kickstand area so horizontal can be run
		sonarPosition=2;
	}//aligns then does horizontal
	//this should def work

	if(sonarPosition==2)
	{
		playSound(soundBeepBeep);
		strafeTo(30);
		coastTo(49.5);
		rotateCoast(85,1);
		coastTo(18);
		coastTo(-7);
		raiseLift();
		dumpAll();
		dumpAll();
		lowerLift();
		strafeTo(-16);
		coastTo(50);
		wait1Msec(200);
		coastTo(-10);
		rotateCoast(90,1);
		coastTo(48);
		strafeTo(-10);
	}

	if(sonarPosition==0)
	{
		coastTo(17);
		coastTo(-5);
//		strafeTo(5);
		brake();
		wait1Msec(500);
		raiseLift();
		advBrakeNeg();
		dumpAll();
		lowerLift();
		strafeTo(-16);
		coastTo(80);
		wait1Msec(200);
		coastTo(-50);
		strafeTo(15);
		coastTo(-72);
	}



}
