#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustom9V)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeft,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     backLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift2,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     frontRight,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     backRight,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     collector,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     collector2,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    rollingGoalPair,      tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    flag,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-sensormux.h"
#include "lego-ultrasound.h"
#include "autonUtils.c"
#include "clampFlagTest.c"

int centerGoalPosition = -1;

float sonargetter;

bool resetPos() {
	coastTo(0.5);
	strafe(left,medium);
	while(floorColor == GRAY){	}
	playSound(soundBeepBeep);
	brake();
	strafeTo(-7);
	coastTo(-5);
	return true;
}
void hitKickstand()
{
		strafeTo(-5);
		startTask(getSonarValues);
		while(sonarVal < 40){
			strafeTo(-3);
		}
		strafeTo(-7);
		stopTask(getSonarValues);
		playSound(soundBeepBeep);
		wait1Msec(1000);
		coastTo(60);
		coastTo(20);
		wait1Msec(200);
		coastTo(-50);
}


task main{
	initializeRobot();
	wait1Msec(100);
	startTask(getHeading);
	startTask(autoRollingGoal);
	//startTask(getSonarValues);
	//wait1Msec(300);
	//stopTask(getSonarValues);
/*
	while(floorColor == NOTGRAY)
		strafeTo(5);
	//strafeTo(10);

	while(true)wait1Msec(1000);
	*/
	servo[dump] = 90;
	coastTo(7);
	strafeTo(50);
	strafeTo(-100);
	strafeTo(12);
	coastTo(75);
	rotateCoast(30,-1);
	coastTo(45);
	coastTo(-45);
	coastTo(45);
	coastTo(-37);
	rotateCoast(10,-1);
	coastTo(22.5);
	while(true)wait1Msec(1000);

}


	//TEST CODE
	/*
	coastTo(20);
	wait1Msec(2000);
	servo[rollingGoalPair]= OPEN;
	wait1Msec(1000);
	servo[rollingGoalPair]= CLAMPED;
	raiseLift();
	servo[dump] =
	*/
	//TEST CODE
