#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S3,     HTSPB,          sensorI2CCustom9V)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     frontRight,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     backRight,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift2,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     frontLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     backLeft,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     collector,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     collector2,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    rollingGoalLeft,      tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    rollingGoalRight,     tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
#include "Robotics (PROGRAMENG)/hitechnic-superpro.h"
int limitOne, limitTwo, limitThree;
int balls = 0;
int binaryPort = 0;
bool waitPorts = false;
bool atBottom = false;

void writeTo(ubyte mask){
//	HTSPBwriteIO(HTSPB,mask);
}

void powerPorts(int ports)
{
	switch(ports){
	case 0: writeTo(0x00); break;
	case 1: writeTo(0x02); break;
	case 2: writeTo(0x06); break;
	case 3: writeTo(0x0e); break;
	case 4: writeTo(0x1e); break;
	case 5: writeTo(0x3e); break;
	}
}

task limitSwitch()
{
	HTSPBsetupIO(HTSPB,0x3E); //b1-b5 out, 0011 1110
	while(true)
	{

	//ball counter
		if(HTSPBreadIO(HTSPB,0x01) >= 1) //b0, 00000001
		{
			balls++;
			playSound(soundBeepBeep);
			//powerPorts(balls);
			waitPorts=true;
		}
	  if(HTSPBreadIO(HTSPB,0x80) >= 1) //b6, 01000000
		{
			balls++;
			//powerPorts(balls);
			waitPorts=true;
		}
		if(HTSPBreadIO(HTSPB,0x40) >= 1) //b7, 10000000
		{
			balls++;
			//powerPorts(balls);
			waitPorts = true;
	  }
		if(waitPorts)
			wait1Msec(200);
		waitPorts=false;

		if(balls == 5)
			HTSPBwriteIO(HTSPB,0x4);

		//ball counter end
			limitOne = HTSPBreadADC(HTSPB, 0, 10);
		if(HTSPBreadADC(HTSPB, 0, 10)>512) //read a0 if pressed
			atBottom = true;
		else atBottom = false;
	}
}
*/
