#pragma config(Sensor, S1,     son1,           sensorSONAR)
#pragma config(Sensor, S2,     son2,           sensorSONAR)
#pragma config(Sensor, S3,     eopdSensor,     sensorAnalog)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-eopd.h"
//#include "include/hitechnic-eopd.h"

task main() {
#ifdef NXT
  nNxtButtonTask  = -2;
#endif

  eraseDisplay();

  displayCenteredTextLine(0, "HiTechnic");
  displayCenteredBigTextLine(1, "EOPD");
  displayCenteredTextLine(3, "Test 1");
  displayCenteredTextLine(5, "Press enter to");
  displayCenteredTextLine(6, "switch between");
  displayCenteredTextLine(7, "ranges");
  sleep(2000);
  eraseDisplay();

  // Create struct to hold sensor data
  tHTEOPD eopdSensor;

  // Initialise and configure struct and port
  // Default mode for  the EOPD is short range
  initSensor(&eopdSensor, S3);

  while(true) {
    if (time1[T1] > 1000) {
      if (eopdSensor.shortRange == false) {
        // set the sensor to short range and display this
      	eopdSensor.shortRange = true;
      	configSensor(&eo  pdSensor);
        displayClearTextLine(1);
        displayTextLine(1, "Short range");
      } else {
        // set the sensor to long range and display this
      	eopdSensor.shortRange = false;
      	configSensor(&eopdSensor);
        displayClearTextLine(1);
        displayTextLine(1, "Long range");
      }
      playSound(soundBeepBeep);
      while(bSoundActive)
      time1[T1] = 0;
    }

#ifdef NXT
    while(nNxtButtonPressed != kEnterButton) {
#else
	  while(!getButtonPress(buttonEnter)) {
#endif
      // Read the sensor values, both the raw and the processed one,
    	// which is linear with the distance detected.  Use the processed
      // value when you want to determine distance to an object
    	readSensor(&eopdSensor);

      displayClearTextLine(3);
      displayClearTextLine(4);
      displayTextLine(4, "Proc:  %4d", eopdSensor.processed);
      displayTextLine(3, "Raw :  %4d", eopdSensor.raw);
      sleep(50);
    }
  }
}

/*
task main()
{
	initSensor(eopd, S3);
	while(true){
		int s1 = SensorValue[son1];
		int s2 = SensorValue[son2];
		int s3 = (s1+s2)/2;
		int eRead = SensorValue[eopd];
		nxtDisplayTextLine(1, "1: %d", s1);
		nxtDisplayTextLine(3, "2: %d", s2);
		nxtDisplayTextLine(5, "A: %d", s3);
		nxtDisplayTextLine(7, "E: %d", eRead);
	}
}
*/
