#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     SMUX,        sensorI2CCustom9V)
#pragma config(Motor,  mtr_S1_C1_1,     frontRight,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     backRight,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift2,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     frontLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     backLeft,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     collector,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     collector2,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    rollingGoalPair,      tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "hitechnic-sensormux.h"
#include "lego-ultrasound.h"
#include "autonUtils.c"

int position;

task main()
{
	wait1Msec(1000);
	please(diagonalTo(24,45));
	position=please(getPosition());


	if(position==2)
	{
		playSound(soundBeepBeep);
		please(strafeTo(36));
		please(coastTo(12));
		please(rotateCoast(90,1));
		please(coastTo(24));
		please(coastTo(-8));
		please(raiseLift());
		please(dumpAll());
		please(dumpAll());
		please(lowerLift());
		please(strafeTo(-36);
		please(coastTo(48));
		please(strafeTo(-60));
	}

	if(position==0)
	{
		while(USreadDist(Sonar)>25){
			motor[frontleft] = 30;
			motor[frontright] = -30;
			motor[backleft] = 30;
			motor[backright] = -30;
		}
		motor[frontleft] = 0;
		motor[frontright] = 0;
		motor[backleft] = 0;
		motor[backright] = 0;
		please(raiseLift());
		please(dumpAll());
		please(dumpAll());
		please(lowerLift());
		please(strafeTo(-16));
		please(coastTo(48));
//		please(coastTo(-100));
	}


}
