#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustom9V)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeft,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     backLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift2,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     frontRight,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     backRight,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     collector,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     collector2,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    rollingGoalPair,      tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    flag,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-sensormux.h"
#include "lego-ultrasound.h"
#include "autonUtils.c"
#include "clampFlagTest.c"

int centerGoalPosition = -1;

float sonargetter;

bool resetPos() {
	coastTo(0.5);
	strafe(left,medium);
	while(floorColor == GRAY){	}
	playSound(soundBeepBeep);
	brake();
	strafeTo(-7);
	coastTo(-5);
	return true;
}
void hitKickstand()
{
		strafeTo(-5);
		startTask(getSonarValues);
		while(sonarVal < 40){
			strafeTo(-3);
		}
		strafeTo(-6);
		stopTask(getSonarValues);
		playSound(soundBeepBeep);
		wait1Msec(1000);
		coastTo(60);
		////tTo(20);
//		startCollector();
		wait1Msec(200);
		coastTo(-70);
	while(true)wait1Msec(1000);
}


task main{
	initializeRobot();
	wait1Msec(100);
	startTask(getHeading);
	startTask(autoRollingGoal);
	//startTask(getSonarValues);
	//wait1Msec(300);
	//stopTask(getSonarValues);
/*
	while(floorColor == NOTGRAY)
		strafeTo(5);
	//strafeTo(10);

	while(true)wait1Msec(1000);
	*/
	servo[dump] = 90;


	coastTo(45);
	wait1Msec(500);
	rotateAlign(0);
	wait1Msec(500);

	//centerGoalPosition = getPosition();
centerGoalPosition = 2;
	//while(true)wait1Msec(1000);

	if(centerGoalPosition==2) //horizontal
	{
		playSound(soundUpwardTones);
		strafeTo(35);
		coastTo(35);
		rotateCoast(1,65);
		coastTo(15);
		coastTo(-6);
		raiseLiftCondition(2350);
		dumpAll();
		dumpAll();
		lowerLiftCondition(1500);
		hitKickstand();
/*
		startTask(getSonarValues);
		while(sonarVal < 100){
			strafeTo(-5);
		}
		stopTask(getSonarValues);
		playSound(soundBeepBeep);
		wait1Msec(1000);
		strafeTo(4);
		coastTo(60);
		wait1Msec(200);
		coastTo(-50);
*/
		/*
		strafeTo(-16);
		coastTo(50);
		wait1Msec(200);
		coastTo(-10);
		rotateCoast(90,1);
		coastTo(48);
		strafeTo(-10);*/
	}
	else if(centerGoalPosition==0) //vertical
	{
		playSound(soundFastUpwardTones);
		strafeTo(7);
		coastTo(9);
		//while(true) wait1Msec(100);
		coastTo(-6);
		brake();
		wait1Msec(500);
		raiseLiftCondition(2350);
		advBrakeNeg();
		dumpAll();
		dumpAll();
		lowerLiftCondition(1500);
		hitKickstand();
	}
	else(centerGoalPosition==1)//45
	{
		playSound(soundDownwardTones);
		strafeTo(30);
		rotateCoast(1,22);
		coastTo(23);
		coastTo(-5);
		//strafeTo(3);
		wait1Msec(500);
		raiseLiftCondition(2300);
		advBrakeNeg();
		dumpAll();
		lowerLiftCondition(1450);
		hitKickstand();
	}

	while(true)wait1Msec(1000);

}


	//TEST CODE
	/*
	coastTo(20);
	wait1Msec(2000);
	servo[rollingGoalPair]= OPEN;
	wait1Msec(1000);
	servo[rollingGoalPair]= CLAMPED;
	raiseLift();
	servo[dump] =
	*/
	//TEST CODE
