#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustom9V)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeft,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     backLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift2,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     frontRight,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     backRight,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     collector,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     collector2,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    rollingGoalPair,      tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    flag,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-sensormux.h"
#include "lego-ultrasound.h"
#include "autonUtils.c"
#include "rollingGoal.c"

bool resetPos() {
	coastTo(0.5);
	strafe(left,medium);
	while(floorColor == GRAY){	}
	playSound(soundBeepBeep);
	brake();
	strafeTo(-14);
	coastTo(-5);
	return true;
}

task main()
{
//6	calm(); //the robot has no chill


/*
raiseLift2();
wait1Msec(1000);
lowerLift2();
*/
//while(true){ }
	centerGoalPosition=-1; //-1 center goals
	initializeRobot(); //political correctness
	startTask(getHeading);
	servo[flag] = 10;
	servo[dump] = 75;
	wait1Msec(1000);
//	agitateUntilCollected();
	waitForStart();
//	resetMonty();
	servo[dump]=75;
	servo[rollingGoalPair] = OPEN;
	coastToCollect(63);// down ramp
	coastTo(-1);


	while(true)wait1Msec(5000);
	wait1Msec(100000000000000000000000000000000000000000000000000);
	//below this is ramp for nonextreme













	startTask(runRollingGoal);
	/*while(true){
		if(nNxtButtonPressed==3) servo[rollingGoalPair] = OPEN;
	}*/
//	servo[rollingGoalPair] = 0;
	coastToCollect(85);// down ramp
	diagonalTo(15, 315);
	diagonalTo(10, 40);
	agitateUntilCollected();//loops until switch is triggered
	raiseLift2();//the sequal to the first lift raiser
	dumpAll();//twice for agitation
	lowerLift2();
	coastTo(-5);
	strafeTo(15);//moves to lane
	rotateCoast(1,-175);
	stopTask(runRollingGoal);
	servo[rollingGoalPair] = OPEN;//letting go
	startTask(runRollingGoal);
	wait1Msec(600);
	rotateCoast(1,170);
	startCollector();
	strafeTo(-20);
	strafeTo(-10);//align with wall
	diagonalTo(18, 40);
	stopCollector();
	agitateUntilCollected();
	servo[rollingGoalPair] = CLAMPED;
	raiseLift();//score on goal
	dumpAll();
	lowerLift();
	strafeTo(8);//moves away from wall
	//rotateAlign(5);
	rotateCoast(1,3);
	coastTo(-130);
	rotateCoast(1,180);
	playSound(soundFastUpwardTones);
	while(true)wait1Msec(1000); // kill program
}
