#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustom9V)
#pragma config(Motor,  mtr_S1_C1_1,     frontRight,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     backRight,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift2,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     frontLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     backLeft,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     collector,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     collector2,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    rollingGoalPair,      tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    flag,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    servo7,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    servo8,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Includes
#include "JoystickDriver.c"
#include "hitechnic-gyro.h"
#include "Collector.c"
#include "RollingGoal.c"
#include "Dump.c"
#include "hitechnic-sensormux.h"
#include "Robotics (PROGRAMENG)/hitechnic-accelerometer.h"
#include "encoderFunctions.c"
//#include "ProtoBoardLogic.c"
#include "driveFunctions.c"
#include "liftFunctions.c"
#include "joyFunctions.c"
#include "lego-touch.h"
//#include "Drivers/hitechnic-eopd.h"
#include "EOPD.c"
#include "clampFlagTest.c"
//#include "JudgesCode.c"


//Global Variables
int deadZone = 15;
//bool pressed;
float slideBtn = 0;
float clampPress = 0;
float globalZ;
float trueZ;
int _x_axis, _y_axis, _z_axis, pitch, tiltCount = 0;
float totalAccel = 0;
const tMUXSensor touchClamp = msensor_S4_1;

//
/*
task flash() {
	while(true){
		HTSPBwriteIO(HTSPB, 0x04);
		wait1Msec(2000);
		HTSPBwriteIO(HTSPB, 0x00);
	}
}*/

int presses = 0;
//bool pressed = false;
bool clamped = false;

float checkMotorEnc() {
	return nMotorEncoder[frontleft];
}

void rotPwr(int pwr) {
	if(pwr>78)pwr = 78;
	if(pwr<0) pwr = 1;
	motor[frontleft] = pwr;
	motor[backleft] = pwr;
	motor[backright] = pwr;
	motor[frontright] = pwr;
}

void freezeEncoders() {
	nMotorEncoder[frontleft] = 0;
	nMotorEncoder[frontright] = 0;
	nMotorEncoder[backleft] = 0;
	nMotorEncoder[backright] = 0;
	playSound(soundBeepBeep);
}

void brake()
{
	motor[frontleft] = 0;
	motor[frontright] = 0;
	motor[backright] = 0;
	motor[backleft] = 0;
}

void encRot(float dist){
	if(dist<0)
	{
		float encval = dist/(16.0*PI)*1120/180*114.5;
		freezeEncoders();
		int motorVal = 0;
		while(abs(checkMotorEnc())<abs(encVal/2))
		{
			motorVal++;
			rotPwr(motorVal);
		}
		while(abs(checkMotorEnc()) > abs(encVal/2)
			&&	abs(checkMotorEnc()) < abs(encVal))
		{
			motorVal--;
			rotPwr(motorVal);
		}
		playSound(soundDownwardTones);
		brake();
		playSound(soundBeepBeep);
	}
	else
	{
		float encval = dist/(16.0*PI)*1120/8.0/30*45;
		freezeEncoders();
		int motorVal = 0;
		while(abs(checkMotorEnc())<abs(encVal/2))
		{
			motorVal++;
			rotPwr(-motorVal);
		}
		while(abs(checkMotorEnc()) > abs(encVal/2))
		{
			motorVal--;
			rotPwr(-motorVal);
		}
		brake();
	}
}



void raiseLift3() {
				motor[motorLift2]=-90;
				motor[motorLift1]=-90;
				wait1Msec(50);
				while(abs(nMotorEncoder[motorLift2])<(1440*2.4 ))
				{
				}
				motor[motorLift1] = 0;
				motor[motorLift2] = 0;
				nMotorEncoder[motorLift2] = 0;
			}
void lowerLift3() {
				motor[motorLift2]=90;
				motor[motorLift1]=90;
				wait1Msec(50);
				while(abs(nMotorEncoder[motorLift2])<(1440*2.4))
				{
				}
				motor[motorLift1] = 0;
				motor[motorLift2] = 0;
				nMotorEncoder[motorLift2] = 0;
}



task main()
{
	initializeRobot();
	startTask(getHeading);
	startTask(FPSDrive);
	startTask(runCollector);
	startTask(runRollingGoal);
	startTask(runDump);
	startTask(Lift);
	//startTask(readEOPD);
//	startTask(flash);
//	HTSPBwriteIO(HTSPB,0x04);
//	waitForStart();
	startTask(joyButtons);
	startTask(autoRollingGoal);

bool isPressed;
while(true){
			if(nNxtButtonPressed == 3) {presses++; wait1Msec(500); isPressed = true;}
			switch(presses)
			{
				case 1: if(isPressed){playSound(soundBeepBeep); nxtDisplayCenteredTextLine(0,"judges code has begun"); motor[collector] = 78; motor[collector2] = -78; wait1Msec(1500); motor[collector] = 0; motor[collector2] = 0; pressed = false;} break;
				case 2: if(isPressed){raiseLift3(); pressed = false; servo[dump] = 180; pressed = false; wait1Msec(500); } break;
				case 3: if(isPressed){servo[dump] = 75; lowerLift3(); pressed = false;} break;
	//			case 4: if(isPressed){ p
				//case 6: if(pressed){ HTSPBwriteIO(HTSPB, 0x04); wait1Msec(1000); HTSPBwriteIO(HTSPB, 0x00); pressed = false; } break;
			}

}
//	pressed = false;
	while(true)
	{
//		pressed = TSreadState(touchClamp);
	}
	wait1Msec(2000000000000000000000000000000);
}
