#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustom9V)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeft,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     backLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift2,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     frontRight,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     backRight,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     collector,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     collector2,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    rollingGoalPair,      tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    flag,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-sensormux.h"
#include "lego-ultrasound.h"
#include "autonUtils.c"
#include "clampFlagTest.c"


bool resetPos() {
	//coastTo(-2);
	//strafe(left,medium);
	while(true)
	{
		if(floorColor == NOTGRAY)
		strafeTo(3);
		//else;
		//if(floorColor ==GRAY) break;
	}
	strafeTo(-5);
	playSound(soundBeepBeep);
	brake();
	return true;
}


task main{
	initializeRobot();
	wait1Msec(100);
	startTask(getHeading);
	startTask(autoRollingGoal);
	startTask(readEOPD);
	strafeTo(45);//arbitrary
	strafeTo(-45)
	//hitKickstand();
	//resetPos();
	//while(true) wait1Msec(100);
	servo[dump] = 75;
	coastToSlow(45);
	wait1Msec(500);
	rotateAlign(0);
	wait1Msec(500);
	strafeTo(1.5);
	centerGoalPosition = getPosition();
	//centerGoalPosition = 2;
	//while(true)wait1Msec(1000);

	if(centerGoalPosition==2) //horizontal
	{
		rotateAlign(0);
		playSound(soundUpwardTones);
		rotateAlign(0);
		strafeTo(35);
		rotateAlign(0);
		coastTo(38);
		//coastTo(4);
		rotateAlign(0);
		rotateCoast(1,60);
		rotateAlignTo(90); //test code to align to kickstand
		coastTo(30);

		//resetPos();
		coastTo(-5);

		raiseLiftCondition(2500);
		dumpAll();
		dumpAll();
		lowerLiftCondition(1500);
		hitKickstand();
		coastTo(-55);
		strafeTo(30);
	while(true){
		strafeTo(15);
		strafeTo(-15);
	}
	}
	else if(centerGoalPosition==0) //vertical
	{
		playSound(soundFastUpwardTones);
		strafeTo(3.5);
		coastTo(13);
		// centerAlign();
		//while(true) wait1Msec(100);
		coastTo(-6);
		brake();
		wait1Msec(500);
		//centerAlign();
		raiseLiftCondition(2350);
		advBrakeNeg();
		dumpAll();
		dumpAll();
		lowerLiftCondition(1500);
		rotateAlign(0);
		hitKickstand();
		coastTo(30);
		rotateCoast(1,180);
		rotateAlign(180);
	while(true){
		strafeTo(15);
		strafeTo(-15);
	}
	}
	else//(centerGoalPosition==1)//45
	{
		playSound(soundDownwardTones);
		rotateAlign(0);
		strafeTo(27);
		rotateAlign(0);
		playSound(soundException);
		//while(true)wait1Msec(2000);
		stopTask(readEOPD);
		rotateCoast(1,20);
		wait1Msec(300);
		coastToSlow(26);
		//strafeTo(3);
		wait1Msec(500);
		//resetPos();
		coastTo(-6);
		raiseLiftCondition(2350); //because short, easy to remember method names make too much sense
		//launchDrones();
		//attackOnSight = true;
		advBrakeNeg();
		dumpAll();
		lowerLiftCondition(1450);
		//coastTo(-5);
		hitKickstand();
		/*
		coastTo(-55);
		strafeTo(30);
	startTask(symphonize);
	while(true){
		strafeTo(15);
		strafeTo(-15);
	}
	*/
	}

}


	//TEST CODE
	/*
	coastTo(20);
	wait1Msec(2000);
	servo[rollingGoalPair]= OPEN;
	wait1Msec(1000);
	servo[rollingGoalPair]= CLAMPED;
	raiseLift();
	servo[dump] =
	*/
	//TEST CODE
