#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
//defines the buttons on the controller

task main()
{
getJoystickSettings(joystick);
//make sure joystick values are updated
while(true)
{
int x = joystick.joy1_x2; //sideways
int y = joystick.joy1_y2; //forward and backward
int z = joystick.joy1_y1; //rotation
//set x y and z to the joystick values
//x is horizontal, y is vertical, 1 and 2 are different buttons

//int left, right;
//motor[frontleft]=-(y+x+z);
//motor[backleft]=-(y-x+z);
//motor[frontright]=(y-x-z);
//motor[backright]=(y+x-z);


//	left = joystick.joy1_y1;
//	right = joystick.joy1_y2;
	motor[motorD] = (y-x-z); //frontright
	motor[motorE] = (y+x-z); //backright
	motor[motorF] = -(y+x+z); //frontleft
	motor[motorG] = -(y-x+z); //backleft
}
}
