#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S3,     SMUX,           sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     lift,          tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C1_2,     hang,          tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_1,     rightFront,    tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_2,     rightBack,     tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_1,     hang2,         tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_2,     flag,          tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C4_1,     leftBack,      tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C4_2,     leftFront,     tmotorTetrix, PIDControl)
#pragma config(Servo,  srvo_S2_C1_1,    autonomous,           tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    hangrelease,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    collector,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    flagout,              tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "Auto Header.h"
#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment\Sample Programs\NXT\3rd Party Sensor Drivers\drivers\hitechnic-sensormux.h"
#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment\Sample Programs\NXT\3rd Party Sensor Drivers\drivers\hitechnic-irseeker-v2.h"
int timeLimit = 0;

const tMUXSensor irSMUX = msensor_S3_1;
void initializeRobot()
{
servo[autonomous]=255;
servo[hangrelease]=0;
servo[collector]=70;
//192
servo[flagout]=255;

//14 Volts when probed by Multimeter
if(externalBatteryAvg > 1380)
timeLimit = 1740;
else
timeLimit = 1780;
return;
}

task main()
{
initializeRobot();
waitForStart();
if(HTSMUXreadPowerStatus(SMUX)){
nxtDisplayString(2,"HI");
}
//HTIRS2readACDir(irSMUX) != 1

//Bring to first basket
time1[T1] = 0;

setSpeed(50,0);


//Check IR
while(HTIRS2readACDir(irSMUX) < 5 && time1[T1] < timeLimit){
}

int x = time1[T1];

setSpeed(50,50);
stopmotors(100);
/*if(x<1200)
{
setSpeed(50,50);
stopmotors(100);
}
else
{	setSpeed(50,50);
stopmotors(100);
}*/
servo[autonomous]=0;

stopmotors(2000);

servo[autonomous]=100;

stopmotors(100);

time1[T1]=0;

setSpeed(-50,0);

while(time1[T1]<x-50) {
}

stopmotors(100);

turn(50,750);

stopmotors(100);

setSpeed(-50,1600);

stopmotors(100);

turn (50,1250);

stopmotors(100);

setSpeed(-75,1700);

stopmotors(100);

/*while(true){
nxtDisplayString(3,"%d",x);
wait10Msec(1);
}*/

}

//14.33 v
//1743


//13.91 v
//1890
//1764
//1819
//1817
