#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S3,     SMUX,           sensorI2CCustom)
#pragma config(Motor,  motorA,          flag1,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          flag2,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          flag3,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     lift,          tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C1_2,     hang,          tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_1,     rightFront,    tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_2,     rightBack,     tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_1,     hang2,         tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     leftBack,      tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C4_2,     leftFront,     tmotorTetrix, PIDControl)
#pragma config(Servo,  srvo_S2_C1_1,    autonomous,           tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    hangrelease,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    collector,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    tilt,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    clamp,                tServoStandard)
#pragma config(Servo,  srvo_S2_C2_1,    open,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "Auto Header 2.11.14.h"
#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment\Sample Programs\NXT\3rd Party Sensor Drivers\drivers\hitechnic-sensormux.h"
#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment\Sample Programs\NXT\3rd Party Sensor Drivers\drivers\hitechnic-irseeker-v2.h"

const tMUXSensor irSMUX = msensor_S3_1;
void initializeRobot()
{
	servo[autonomous]=255;
	servo[hangrelease]=0;
	servo[clamp]=120;
	servo[tilt]=0;
	servo[collector]=231;
	servo[open]=255;
	return;
}

task main()
{
	initializeRobot();

	wait10Msec(150);
	//waitForStart();
	if(HTSMUXreadPowerStatus(SMUX)){
		nxtDisplayString(2,"HI");
	}
	//HTIRS2readACDir(irSMUX) != 1

	//Bring to first basket
	setSpeed(50,500);
	stopmotors(400);

	//Check IR
	if(HTIRS2readACDir(irSMUX) < 1){
		setSpeed(70, 2500);
		stopmotors(300);

		for(int x = 0; x < 4; x ++){
			//Sees IR?
			if(HTIRS2readACDir(irSMUX) == 5){
				nxtDisplayString(3, "%d", HTIRS2readACDir(irSMUX));
				//Dispense IR Block
				servo[autonomous]=0;

				stopmotors(600);

				servo[autonomous]=100;

				stopmotors(100);

				} else{
				switch(x){

				/*case 0:
					//Move to 2nd Basket
					//setSpeed(50,425);
					setSpeed(30,500);
					stopmotors(300);

					break;

				case 1:
					//Move to 3rd Basket
					//setSpeed(50,700);
					setSpeed(30,700);
					stopmotors(300);
					break;

				*/case 0:
					//Move to 4th Basket
					//setSpeed(50,400);
					setSpeed(30,600);
					stopmotors(400);
					break;

				default:
					stopmotors(300);
					break;
				}
			}

		}
	}

	else{
		//1st basket
		setSpeed(50,500);
		stopmotors(1000);

		for(int x = 0; x < 4; x ++){
			//Sees IR?
			if(HTIRS2readACDir(irSMUX) == 5){
				nxtDisplayString(3, "%d", HTIRS2readACDir(irSMUX));
				//Dispense IR Block
				servo[autonomous]=0;

				stopmotors(1000);

				servo[autonomous]=100;

				stopmotors(100);

				} /*else{
				switch(x){

				case 0:
					//Move to 2nd Basket
					//setSpeed(50,425);
					setSpeed(30,500);
					stopmotors(300);

					break;

				case 1:
					//Move to 3rd Basket
					//setSpeed(50,700);
					setSpeed(30,700);
					stopmotors(300);
					break;

				case 2:
					//Move to 4th Basket
					//setSpeed(50,400);
					setSpeed(30,600);
					stopmotors(400);
					break;

				default:
					stopmotors(300);
					break;
				}
			}
*/
		}
	}


	while(/*HTIRS2readDCDir(irSMUX) < 5*/true){
		nxtDisplayString(3, "%d", HTIRS2readACDir(irSMUX) );
		wait1Msec(10);
	}

	stopmotors(250);



}
