#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S3,     SMUX,           sensorI2CCustom)
#pragma config(Sensor, S4,     judge,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     lift,          tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C1_2,     hang,          tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_1,     rightFront,    tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_2,     rightBack,     tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_1,     hang2,         tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_2,     flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     leftBack,      tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C4_2,     leftFront,     tmotorTetrix, PIDControl)
#pragma config(Servo,  srvo_S2_C1_1,    autonomous,           tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    hangrelease,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    collector,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    tilt,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    clamp,                tServoStandard)
#pragma config(Servo,  srvo_S2_C2_1,    open,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#define JOYSTICK_UPDATE_TIME 10


void initializeRobot()
{
	// Place code here to initialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	servo[autonomous]=100;
	servo[hangrelease]=0;
	servo[clamp]=120;
	servo[tilt]=0;
	servo[collector]=231;
	servo[open]=255;
	return;
}

task main()
{
	initializeRobot();

	//	waitForStart();   // wait for start of tele-op phase
	getJoystickSettings(joystick);

	while(SensorValue(judge)==0){}

	//first click
	motor[rightBack]=50;
	motor[rightFront]=50;
	motor[leftBack]=-50;
	motor[leftFront]=-50;
	wait1Msec(500);

	motor[rightBack]=-50;
	motor[rightFront]=-50;
	motor[leftBack]=50;
	motor[leftFront]=50;
	wait1Msec(500);

	motor[rightBack]=-50;
	motor[rightFront]=-50;
	motor[leftBack]=-50;
	motor[leftFront]=-50;
	wait1Msec(500);

	motor[rightBack]=50;
	motor[rightFront]=50;
	motor[leftBack]=50;
	motor[leftFront]=50;
	wait1Msec(500);

	motor[rightBack]=0;
	motor[rightFront]=0;
	motor[leftBack]=0;
	motor[leftFront]=0;
	wait1Msec(500);
	//end first click


	//start second click
	while(SensorValue(judge)==0){}
	servo[collector]=10; // collector down
	wait1Msec(500);
	while(SensorValue(judge)==0){}
	servo[clamp]=90; // open clamp
	wait1Msec(500);
	while(SensorValue(judge)==0){}
	servo[clamp]=120;		// close clamp
	wait1Msec(500);
	while(SensorValue(judge)==0){}
	motor[lift]=-100; //elevator up
	wait1Msec(3250);
	motor[lift]=0; //stop elevator
	wait1Msec(500);
	while(SensorValue(judge)==0){}
	servo[tilt]=125; 	//tilt
	wait1Msec(500);
	while(SensorValue(judge)==0){}
	servo[clamp]=90; //open clamp
	wait1Msec(500);
	while(SensorValue(judge)==0){}
	servo[tilt]=0; //un tilt
	wait1Msec(500);
	while(SensorValue(judge)==0){}
	motor[lift]=100; //elevator down
	wait1Msec(2850);
	motor[lift]=0; //elevator stop
	wait1Msec(500);
	while(SensorValue(judge)==0){}
	servo[clamp]=120; //close clamp
	wait1Msec(500);
	while(SensorValue(judge)==0){}
	servo[collector]=231; //collectdor up
	wait1Msec(500);
	//end second click

	//start third click
	while(SensorValue(judge)==0){}
	servo[hangrelease]=210; //middle release
	wait1Msec(500);
	while(SensorValue(judge)==0){}
	servo[hangrelease]=255; //complete release
	wait1Msec(500);
	/*while(SensorValue(judge)==0){}
	motor[hang]=100; //pull
	motor[hang2]=-100;
	wait1Msec(500);
	while(SensorValue(judge)==0){}
	motor[hang]=-100; //release
	motor[hang2]=100;
	wait1Msec(500);*/
	//end third Click

	//start 4th click
	while(SensorValue(judge)==0){}
	servo[open]=145; //open flag raiser
	wait1Msec(500);
	while(SensorValue(judge)==0){}
	motor[flag]=100; //spin flag
	wait1Msec(1000);
	motor[flag]=0;  //stop flag
	wait1Msec(500);
	while(SensorValue(judge)==0){}
	servo[open]=255; //close flag raiser
	wait1Msec(500);
	//end fourth click

	//start fifth click
	while(SensorValue(judge)==0){}
	wait1Msec(1000);
	servo[autonomous]=0;
	wait1Msec(500);
	servo[autonomous]=253;
	wait1Msec(500);
	//end 5th click

}
